### ISSUE TITLE
JS issue

### ISSUE THREAD

**Issue by JosephDSmith** [learn-co-curriculum/phase-1-arrow-functions#14]
### Canvas Link

https://learning.flatironschool.com/courses/6206/assignments/230818?module_item_id=539798

### Concern

This is the material from your lesson:

"Second, when there are no braces, arrow functions have an implicit return, i.e., they automatically return the result of the last expression! This is the only situation in which a JavaScript function doesn't require explicit return with the return keyword."

This is not true - there are multiple array methods (which are functions) which return values automatically (push, shift, pop, and unshift).

**Comment by lizbur10** [comment]
Hi @JosephDSmith! Nice observation! But there actually is an explicit return with those methods - it's just built into the method so we don't see it. If you take a look at the code that underlies array methods (e.g., [.pop](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.pop)), you will see that the last step is an explicit return. 💙
