### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by thakaj** [learn-co-curriculum/phase-1-arrow-functions#3]
const squares = nums.map(x => x ** 2);

x ** 2);

I believe that there should only be one * but I may be wrong. Thank you!

**Comment by lizbur10** [comment]
Hi there! A single * is used for multiplication, while the ** syntax is another way of expressing an exponent. So x**2 is the same as x*x ("x squared"), x**3 is the same as x*x*x ("x cubed"), etc. 

I hope this helps! 😃
